/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp2_projeto;

/**
 *
 * @author mathe
 */

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;

public class FormularioUsuario extends JPanel {
    private JTextField campoNome;
    private JTextField campoEmail;
    private JTextField campoTelefone;
    private JTextField campoDataNascimento;
    private boolean confirmado;

    public FormularioUsuario(Usuario usuario) {
        setLayout(new GridLayout(4, 1, 0, 20));

        add(new JLabel("Nome:"));
        campoNome = new JTextField(usuario != null ? usuario.getNome() : "");
        add(campoNome);

        add(new JLabel("Email:"));
        campoEmail = new JTextField(usuario != null ? usuario.getEmail() : "");
        add(campoEmail);

        add(new JLabel("Telefone:"));
        campoTelefone = new JTextField(usuario != null ? usuario.getTelefone() : "");
        add(campoTelefone);

        add(new JLabel("Data de Nascimento (yyyy-MM-dd):"));
        campoDataNascimento = new JTextField(usuario != null ? usuario.getDataNascimento().toString() : "");
        add(campoDataNascimento);
    }

    public boolean mostrar() {
        int opcao = JOptionPane.showConfirmDialog(
            null,
            this,
            "Formulário de Usuário",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        confirmado = (opcao == JOptionPane.OK_OPTION);
        return confirmado;
    }

    public String getNome() {
        return campoNome.getText();
    }

    public String getEmail() {
        return campoEmail.getText();
    }

    public String getTelefone() {
        return campoTelefone.getText();
    }

    public LocalDate getDataNascimento() {
        try {
            return LocalDate.parse(campoDataNascimento.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida. Use o formato yyyy-MM-dd.");
            return null;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

